(function(){
  const KEY='fluency-cloud-v2',LEGACY_KEY='fluency-cloud-v1';let syncing=false,bootstrapData=null;
  const oldPut=put;
  put=async function(value){const result=await oldPut(value);if(!syncing&&value&&value.id&&value.transcript&&configured())cloudSave(value).catch(function(e){setStatus('Cloud save pending: '+e.message,false)});return result};

  function saved(){try{return Object.assign({},JSON.parse(localStorage.getItem(KEY)||'{}'),JSON.parse(sessionStorage.getItem('fluency-auth-v2')||'{}'))}catch(e){return{}}}
  function store(c){const prefs=Object.assign({},c);['token','sessionToken','sessionExpiry','email'].forEach(k=>delete prefs[k]);localStorage.setItem(KEY,JSON.stringify(prefs));localStorage.removeItem(LEGACY_KEY);sessionStorage.setItem('fluency-auth-v2',JSON.stringify({sessionToken:c.sessionToken,sessionExpiry:c.sessionExpiry,email:c.email}))}
  function endpoint(){return String(window.FLUENCY_CONFIG?.backendUrl||'').trim().replace(/\/$/,'')}
  function sessionValid(c){return Boolean(c.sessionToken&&Number(c.sessionExpiry||0)>Date.now()+1000)}
  function configured(){return Boolean(endpoint()&&sessionValid(saved())&&window.FluencyAccess.isReady())}
  function auth(c){c=c||saved();return sessionValid(c)?{sessionToken:c.sessionToken}:{}}
  function readForm(){const c=saved(),criteria={};document.querySelectorAll('.criterion').forEach(x=>criteria[x.value]=x.checked);return Object.assign({},c,{retentionDays:Number($('retentionDays').value)||7,model:$('geminiModel').value||'gemini-3.1-flash-lite',criteria,custom:$('aiCustom').value.trim()})}
  function fillForm(){const c=saved();$('retentionDays').value=String(c.retentionDays||7);const allowed=['gemini-3.5-flash-lite','gemini-3.1-flash-lite'];$('geminiModel').value=allowed.includes(c.model)?c.model:'gemini-3.1-flash-lite';$('aiCustom').value=c.custom||'';document.querySelectorAll('.criterion').forEach(x=>{if(c.criteria&&Object.prototype.hasOwnProperty.call(c.criteria,x.value))x.checked=Boolean(c.criteria[x.value])});accountUI(c)}
  function setStatus(text,ok){$('cloudStatus').textContent=text;$('cloudStatus').className='note '+(ok?'cloud-ok':'cloud-warn');if(document.documentElement.classList.contains('auth-locked'))$('loginStatus').textContent=text}
  function accountUI(c){const signed=configured();$('signedInPanel').hidden=!signed;$('signedInEmail').textContent=signed?c.email:'';$('accountBadge').textContent=signed?c.email:'Sign-in required'}
  async function post(payload,skipAuth){const c=saved(),url=endpoint();if(!url)throw Error('Permanent Google backend is not configured.');if(!skipAuth){if(!sessionValid(c))throw Error('Sign in with Google first.');Object.assign(payload,auth(c));}await fetch(url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)})}
  function jsonp(action,params,timeout,skipAuth){return new Promise(function(resolve,reject){const c=saved(),url=endpoint();if(!url)return reject(Error('Permanent Google backend is not configured.'));const name='fluencyCb'+Date.now()+Math.random().toString(36).slice(2),script=document.createElement('script'),timer=setTimeout(()=>done(Error('Google backend timed out.')),timeout||25000);function done(err,data){clearTimeout(timer);delete window[name];script.remove();err?reject(err):resolve(data)}window[name]=data=>{if(data?.error==='UNAUTHORIZED')lockSession('Your session expired or access was removed. Sign in again.');data&&data.ok===false?done(Error(data.error||'Google request failed')):done(null,data)};script.onerror=()=>done(Error('Could not reach Google backend.'));const q=new URLSearchParams(Object.assign({},params||{},skipAuth?{}:auth(c),{action:action,callback:name}));script.referrerPolicy='no-referrer';script.src=url+'?'+q.toString();document.head.appendChild(script)})}
  async function blobData(b){return new Promise(function(resolve,reject){const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(b)})}
  async function cloudSave(row){setStatus('Saving session to Google…',true);const copy=Object.assign({},row,{audioDataUrl:row.audio?await blobData(row.audio):null});delete copy.audio;delete copy.aiReview;delete copy.aiStatus;await post({action:'save',session:copy});const check=await jsonp('list',{},45000);if(!(check.sessions||[]).some(x=>x.id===row.id&&x.transcript===row.transcript))throw Error('Google has not confirmed the saved session. Retry Sync history.');setStatus('Session saved to Google. Transcript is permanent; retained audio follows the selected expiry.',true)}

  let expiryTimer=null;
  function lockSession(message){window.FluencyAccess.lock(message);sessionStorage.removeItem('fluency-auth-v2');clearTimeout(expiryTimer);accountUI({})}
  async function validateSession(){const result=await jsonp('session',{},20000);if(result.authVersion!=='google-v2'||!result.storageKey)throw Error('The Google backend needs the secure-login update.');const c=saved();Object.assign(c,{email:result.email,sessionExpiry:result.expiresAt});store(c);await window.FluencyAccess.unlock(result.storageKey);expiryTimer=setTimeout(()=>{lockSession('Session expired. Sign in again.');location.reload()},Math.max(1,result.expiresAt-Date.now()));fillForm();await render()}
  async function bootstrap(){if(!endpoint())return setStatus('Google backend is not configured.',false);try{bootstrapData=await jsonp('bootstrap',{},20000,true);if(bootstrapData.authVersion!=='google-v2')throw Error('The Google backend needs the secure-login update.');if(bootstrapData.googleClientId)renderGoogleButton(bootstrapData.googleClientId);else setStatus('Google sign-in setup is awaiting an OAuth client ID.',false);if(sessionValid(saved())){await validateSession();await sync()}else setStatus(bootstrapData.googleClientId?'Sign in with your approved Google account.':'Google sign-in setup is awaiting an OAuth client ID.',false)}catch(e){lockSession('Sign-in unavailable: '+e.message)}}
  function renderGoogleButton(clientId){let tries=0;(function wait(){if(window.google&&google.accounts&&google.accounts.id){google.accounts.id.initialize({client_id:clientId,callback:handleGoogleCredential,auto_select:false,cancel_on_tap_outside:false});google.accounts.id.renderButton($('googleSignInButton'),{theme:'outline',size:'large',shape:'pill',text:'continue_with',width:280});return}if(tries++<40)setTimeout(wait,250);else setStatus('Google sign-in could not load. Check your connection and reload.',false)})()}
  window.handleGoogleCredential=async function(response){const nonce=crypto.randomUUID();setStatus('Verifying your approved Google account…',true);try{await post({action:'signin',credential:response.credential,nonce},true);let result=null;for(let i=0;i<12;i++){await new Promise(r=>setTimeout(r,500));const x=await jsonp('signinResult',{nonce},8000,true);if(x.status!=='PENDING'){result=x;break}}if(!result?.ok)throw Error(result?.error||'Account verification did not complete.');const c=saved();Object.assign(c,{sessionToken:result.sessionToken,sessionExpiry:Date.now()+Number(result.expiresIn)*1000,email:result.email});store(c);await validateSession();setStatus('Connected as '+result.email+'.',true);await sync()}catch(e){lockSession('Google sign-in failed: '+e.message)}};
  async function signOut(){try{await post({action:'signout'})}catch(e){}finally{lockSession('Signed out.');if(window.google?.accounts)google.accounts.id.disableAutoSelect();location.reload()}}
  document.addEventListener('visibilitychange',async()=>{if(!document.hidden&&window.FluencyAccess.isReady()){try{await validateSession()}catch(e){lockSession('Sign in again to reopen your workspace.')}}});
  async function saveConfig(){const c=readForm();store(c);setStatus('Preferences saved.',true);if(!configured())return;try{await post({action:'config',retentionDays:c.retentionDays,model:c.model})}catch(e){setStatus('Saved locally; server update could not be confirmed.',false)}}
  async function test(){await saveConfig();if(!configured())return;setStatus('Testing Google backend…',true);try{const r=await jsonp('health');if(!r.ok)throw Error(r.error||'Connection failed');setStatus('Connected: database ✓ Drive ✓ Gemini '+(r.geminiConfigured?'✓':'key missing')+' • '+r.retentionDays+'-day audio retention • '+r.model,r.geminiConfigured)}catch(e){setStatus('Connection failed: '+e.message,false)}}
  async function sync(){if(!configured())return setStatus('Sign in with Google to synchronize history.',false);setStatus('Synchronizing local and Google history…',true);try{const r=await jsonp('list',{},45000);if(!r.ok)throw Error(r.error||'Sync failed');const local=await all(),byId=new Map(local.map(x=>[x.id,x])),remoteIds=new Set(r.sessions.map(x=>x.id));syncing=true;for(const remote of r.sessions){const prior=byId.get(remote.id);await oldPut(Object.assign({},prior||{},remote,{audio:prior&&prior.audio?prior.audio:null,cloudOnly:!prior}))}for(const row of local){if(!remoteIds.has(row.id))await cloudSave(row)}syncing=false;await render();updateFocus(r.sessions);document.dispatchEvent(new Event('fluency-cloud-synced'));setStatus((new Set(local.map(x=>x.id).concat(r.sessions.map(x=>x.id)))).size+' sessions synchronized.',true)}catch(e){syncing=false;setStatus('Sync failed: '+e.message,false)}}
  function updateFocus(rows){const latest=(rows||[]).filter(x=>x.aiReview&&x.aiStatus==='DONE').sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))[0];if(!latest)return;const r=latest.aiReview||{},leak=r.primaryLeak||r.primaryLever||'No major leak identified',drill=r.drill&&r.drill.instruction||r.assignedDrill||r.practiceChallenge||'Repeat the message once, more crisply.';$('latestLeak').textContent=leak;$('currentFocusTitle').textContent=String(r.drill&&r.drill.name||'NEXT COMMUNICATION LEVER').toUpperCase();$('currentFocusText').textContent=drill}

  function rubric(){const c=saved();return{model:c.model||'gemini-3.5-flash-lite',criteria:c.criteria||{},custom:c.custom||'',analysisVersion:'2.0',rubricVersion:'crisp-sharp-impactful-v1',mode:$('context').value}}
  async function analyzeWithAI(){
    const transcript=$('transcript').value.trim();if(!transcript)return toast('Record or enter a transcript first.');
    const id=$('sessionId').value||crypto.randomUUID();$('sessionId').value=id;
    const prior=(await all()).find(x=>x.id===id)||{};
    const row=Object.assign({},prior,window.FluencyV23?.activeTelegram||{},{id,createdAt:prior.createdAt||new Date().toISOString(),groupId:$('groupId').value,attempt:Number($('attemptNo').value)||1,title:$('title').value.trim()||'Untitled sample',context:$('context').value,audience:$('audience').value.trim(),duration,transcript,timestampedTranscript:$('timestampedTranscript').value.trim(),reflection:$('reflection').value.trim(),tags:$('tags').value.trim(),metrics:analyze(),wordTimestamps:window.getFluencyWordTimestamps?.()||[],audio:$('retainAudio').checked?blob:prior.audio||null});
    $('aiReviewBtn').disabled=true;$('aiStatus').textContent='Saving session and starting communication review…';
    try{await oldPut(row);const result=await window.FluencyReviews.run(row,'all','',msg=>$('aiStatus').textContent=msg);renderAI(result);updateFocus([{aiReview:result,aiStatus:'DONE',updatedAt:new Date().toISOString()}]);$('aiStatus').textContent='Communication review complete and linked to this session.'}
    catch(e){$('aiStatus').textContent='AI review unavailable: '+e.message}finally{$('aiReviewBtn').disabled=false}
  }
  window.FluencyCloud={jsonp,post,configured,cloudSave,saveLocal:oldPut,rubric,updateFocus,auth};
  function block(label,value,cls){return value?'<div class="coach '+(cls||'')+'"><b>'+esc(label)+'</b><span>'+esc(String(value))+'</span></div>':''}
  function renderAI(r){const scores=r.scores||{},scoreHtml=Object.entries(scores).filter(([,v])=>v!==null&&v!==undefined&&v!=='').map(([k,v])=>'<div><b>'+esc(String(v))+'</b><span>'+esc(k.replace(/([A-Z])/g,' $1'))+'</span></div>').join(''),worked=(r.whatWorked||r.strengths||[]).slice(0,2).join(' • '),drill=r.drill||{},compression=r.compression||{};$('aiResult').innerHTML='<h3>Crisp • Sharp • Impactful coaching</h3><p>'+esc(r.summary||'')+'</p><div class="review-grid">'+scoreHtml+'</div>'+block('What worked',worked,'strength')+block('Primary communication leak',r.primaryLeak||r.primaryLever,'focus')+block('Evidence',(r.evidence||[]).join(' • '),'')+block('Compression',compression.assessment||r.compressionAssessment,'')+(compression.rewrite?'<h4>Compressed version</h4><p class="detail-text">'+esc(compression.rewrite)+'</p>':'')+'<h4>Executive version</h4><p class="detail-text">'+esc(r.executiveVersion||r.tighterVersion||'')+'</p>'+(r.punchyVersion?'<h4>Punchy version</h4><p class="detail-text">'+esc(r.punchyVersion)+'</p>':'')+block('One drill',(drill.name?drill.name+': ':'')+(drill.instruction||r.assignedDrill||r.practiceChallenge||''),'challenge');$('aiResult').hidden=false}

  document.addEventListener('DOMContentLoaded',function(){fillForm();$('saveCloudBtn').onclick=saveConfig;$('testCloudBtn').onclick=test;$('syncCloudBtn').onclick=sync;$('aiReviewBtn').onclick=analyzeWithAI;$('signOutBtn').onclick=signOut;store(saved());bootstrap()});
})();
