(function(){
  const KEY='fluency-cloud-v1';let syncing=false;
  const oldPut=put;
  put=async function(value){const result=await oldPut(value);if(!syncing&&value&&value.id&&value.transcript&&configured())cloudSave(value).catch(function(e){setStatus('Cloud save pending: '+e.message,false)});return result};

  function config(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}}
  function configured(){const c=config();return Boolean(c.url&&c.token)}
  function normalizedUrl(v){return String(v||'').trim().replace(/\/$/,'')}
  function readForm(){const criteria={};document.querySelectorAll('.criterion').forEach(x=>criteria[x.value]=x.checked);return{url:normalizedUrl($('cloudUrl').value),token:$('cloudToken').value.trim(),retentionDays:Number($('retentionDays').value)||7,model:$('geminiModel').value.trim()||'gemini-2.5-flash',criteria:criteria,custom:$('aiCustom').value.trim()}}
  function fillForm(){const c=config();$('cloudUrl').value=c.url||'';$('cloudToken').value=c.token||'';$('retentionDays').value=String(c.retentionDays||7);$('geminiModel').value=c.model||'gemini-2.5-flash';$('aiCustom').value=c.custom||'';document.querySelectorAll('.criterion').forEach(x=>{if(c.criteria&&Object.prototype.hasOwnProperty.call(c.criteria,x.value))x.checked=Boolean(c.criteria[x.value])});setStatus(configured()?'Cloud configured. Test the connection or sync history.':'Cloud backend is not configured. Local recording remains available.',configured())}
  function setStatus(text,ok){$('cloudStatus').textContent=text;$('cloudStatus').className='note '+(ok?'cloud-ok':'cloud-warn')}
  async function post(payload){const c=config();if(!c.url||!c.token)throw Error('Configure the Google backend first.');payload.token=c.token;await fetch(c.url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)})}
  function jsonp(action,params,timeout){return new Promise(function(resolve,reject){const c=config();if(!c.url||!c.token)return reject(Error('Configure the Google backend first.'));const name='fluencyCb'+Date.now()+Math.random().toString(36).slice(2),script=document.createElement('script'),timer=setTimeout(done,timeout||25000);function done(err,data){clearTimeout(timer);delete window[name];script.remove();err?reject(err):resolve(data)}window[name]=data=>done(null,data);script.onerror=()=>done(Error('Could not reach Google backend.'));const q=new URLSearchParams(Object.assign({},params||{},{action:action,token:c.token,callback:name}));script.src=c.url+'?'+q.toString();document.head.appendChild(script)})}
  async function blobData(b){return new Promise(function(resolve,reject){const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(b)})}
  async function cloudSave(row){setStatus('Saving session to Google…',true);const copy=Object.assign({},row,{audioDataUrl:row.audio?await blobData(row.audio):null});delete copy.audio;await post({action:'save',session:copy});setStatus('Session sent to Google. Transcript is permanent; retained audio follows the selected expiry.',true)}

  async function saveConfig(){const c=readForm();if(!c.url||!c.token)return setStatus('Backend URL and access token are required.',false);localStorage.setItem(KEY,JSON.stringify(c));setStatus('Configuration saved on this device.',true);try{await post({action:'config',retentionDays:c.retentionDays,model:c.model})}catch(e){setStatus('Saved locally; server update could not be confirmed.',false)}}
  async function test(){await saveConfig();setStatus('Testing Google backend…',true);try{const r=await jsonp('health');if(!r.ok)throw Error(r.error||'Connection failed');setStatus('Connected: database ✓ Drive ✓ Gemini '+(r.geminiConfigured?'✓':'key missing')+' • '+r.retentionDays+'-day audio retention • '+r.model,r.geminiConfigured)}catch(e){setStatus('Connection failed: '+e.message,false)}}
  async function sync(){if(!configured())return setStatus('Configure the backend first.',false);setStatus('Syncing permanent transcript history…',true);try{const r=await jsonp('list',{},45000);if(!r.ok)throw Error(r.error||'Sync failed');const local=await all(),byId=new Map(local.map(x=>[x.id,x]));syncing=true;for(const remote of r.sessions){const prior=byId.get(remote.id);await oldPut(Object.assign({},prior||{},remote,{audio:prior&&prior.audio?prior.audio:null,cloudOnly:!prior}))}syncing=false;await render();setStatus(r.sessions.length+' cloud sessions synchronized.',true)}catch(e){syncing=false;setStatus('Sync failed: '+e.message,false)}}

  function rubric(){const c=config();return{model:c.model||'gemini-2.5-flash',criteria:c.criteria||{},custom:c.custom||''}}
  async function analyzeWithAI(){if(!configured())return toast('Configure the Google backend in Settings first.');const transcript=$('transcript').value.trim();if(!transcript)return toast('Record or enter a transcript first.');const jobId=crypto.randomUUID();$('aiReviewBtn').disabled=true;$('aiStatus').textContent='Gemini is reviewing the transcript…';$('aiResult').hidden=true;try{await post({action:'analyze',jobId:jobId,transcript:transcript,metrics:typeof lastMetrics!=='undefined'?lastMetrics:analyze(),rubric:rubric()});const end=Date.now()+90000;let result;while(Date.now()<end){await new Promise(r=>setTimeout(r,2500));const j=await jsonp('job',{jobId:jobId});if(j.status==='DONE'){result=j.result;break}if(j.status==='ERROR')throw Error(j.error||'Gemini review failed')}if(!result)throw Error('Review is still processing. Try again shortly.');renderAI(result);$('aiStatus').textContent='Gemini review complete.'}catch(e){$('aiStatus').textContent='AI review unavailable: '+e.message}finally{$('aiReviewBtn').disabled=false}}
  function renderAI(r){const scores=r.scores||{},scoreHtml=Object.entries(scores).map(([k,v])=>'<div><b>'+esc(String(v))+'</b><span>'+esc(k.replace(/([A-Z])/g,' $1'))+'</span></div>').join('');$('aiResult').innerHTML='<h3>Gemini coaching</h3><p>'+esc(r.summary||'')+'</p><div class="review-grid">'+scoreHtml+'</div><div class="coach strength"><b>Strengths</b><span>'+esc((r.strengths||[]).join(' • '))+'</span></div><div class="coach focus"><b>Primary lever</b><span>'+esc(r.primaryLever||'')+'</span></div><h4>Evidence</h4><ul>'+(r.evidence||[]).map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul><h4>Tighter version</h4><p class="detail-text">'+esc(r.tighterVersion||'')+'</p><div class="coach challenge"><b>Practice challenge</b><span>'+esc(r.practiceChallenge||'')+'</span></div>';$('aiResult').hidden=false}

  document.addEventListener('DOMContentLoaded',function(){fillForm();$('saveCloudBtn').onclick=saveConfig;$('testCloudBtn').onclick=test;$('syncCloudBtn').onclick=sync;$('aiReviewBtn').onclick=analyzeWithAI;if(configured())setTimeout(sync,1000)});
})();
