(function(){
  const KEY='fluency-cloud-v2',LEGACY_KEY='fluency-cloud-v1';let syncing=false,bootstrapData=null;
  const oldPut=put;
  put=async function(value){const result=await oldPut(value);if(!syncing&&value&&value.id&&value.transcript&&configured())cloudSave(value).catch(function(e){setStatus('Cloud save pending: '+e.message,false)});return result};

  function saved(){try{return Object.assign({},JSON.parse(localStorage.getItem(LEGACY_KEY)||'{}'),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return{}}}
  function store(c){localStorage.setItem(KEY,JSON.stringify(c))}
  function endpoint(){return String((window.FLUENCY_CONFIG&&window.FLUENCY_CONFIG.backendUrl)||saved().url||'').trim().replace(/\/$/,'')}
  function sessionValid(c){return Boolean(c.sessionToken&&Number(c.sessionExpiry||0)>Date.now()+30000)}
  function configured(){const c=saved();return Boolean(endpoint()&&(sessionValid(c)||c.token))}
  function auth(c){c=c||saved();return sessionValid(c)?{sessionToken:c.sessionToken}:{token:c.token||''}}
  function readForm(){const c=saved(),criteria={};document.querySelectorAll('.criterion').forEach(x=>criteria[x.value]=x.checked);return Object.assign({},c,{url:endpoint()||String($('cloudUrl').value||'').trim().replace(/\/$/,''),token:$('cloudToken').value.trim()||c.token||'',retentionDays:Number($('retentionDays').value)||7,model:$('geminiModel').value||'gemini-3.5-flash-lite',criteria:criteria,custom:$('aiCustom').value.trim()})}
  function fillForm(){const c=saved();$('cloudUrl').value=endpoint();$('cloudToken').value=c.token||'';$('retentionDays').value=String(c.retentionDays||7);const allowed=['gemini-3.5-flash-lite','gemini-3.1-flash-lite'];$('geminiModel').value=allowed.includes(c.model)?c.model:'gemini-3.5-flash-lite';$('aiCustom').value=c.custom||'';document.querySelectorAll('.criterion').forEach(x=>{if(c.criteria&&Object.prototype.hasOwnProperty.call(c.criteria,x.value))x.checked=Boolean(c.criteria[x.value])});accountUI(c);setStatus(configured()?(sessionValid(c)?'Google account linked. Database and Drive reconnect automatically.':'Cloud configured through legacy access. Sign in with Google to finish migration.'):(endpoint()?'Sign in with Google to connect your database.':'Permanent backend endpoint is awaiting one-time configuration.'),configured())}
  function setStatus(text,ok){$('cloudStatus').textContent=text;$('cloudStatus').className='note '+(ok?'cloud-ok':'cloud-warn')}
  function accountUI(c){const signed=sessionValid(c);$('signedInPanel').hidden=!signed;$('signedInEmail').textContent=signed?(c.email||'Google account linked'):'';$('accountBadge').textContent=signed?(c.email||'Google linked'):(configured()?'Cloud linked':'Local mode')}
  async function post(payload,skipAuth){const c=saved(),url=endpoint();if(!url)throw Error('Permanent Google backend is not configured.');if(!skipAuth)Object.assign(payload,auth(c));await fetch(url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)})}
  function jsonp(action,params,timeout,skipAuth){return new Promise(function(resolve,reject){const c=saved(),url=endpoint();if(!url)return reject(Error('Permanent Google backend is not configured.'));const name='fluencyCb'+Date.now()+Math.random().toString(36).slice(2),script=document.createElement('script'),timer=setTimeout(()=>done(Error('Google backend timed out.')),timeout||25000);function done(err,data){clearTimeout(timer);delete window[name];script.remove();err?reject(err):resolve(data)}window[name]=data=>done(null,data);script.onerror=()=>done(Error('Could not reach Google backend.'));const q=new URLSearchParams(Object.assign({},params||{},skipAuth?{}:auth(c),{action:action,callback:name}));script.src=url+'?'+q.toString();document.head.appendChild(script)})}
  async function blobData(b){return new Promise(function(resolve,reject){const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(b)})}
  async function cloudSave(row){setStatus('Saving session to Google…',true);const copy=Object.assign({},row,{audioDataUrl:row.audio?await blobData(row.audio):null});delete copy.audio;await post({action:'save',session:copy});setStatus('Session sent to Google. Transcript is permanent; retained audio follows the selected expiry.',true)}

  async function bootstrap(){if(!endpoint())return fillForm();try{bootstrapData=await jsonp('bootstrap',{},20000,true);if(!bootstrapData.ok)throw Error(bootstrapData.error||'Bootstrap failed');if(bootstrapData.googleClientId)renderGoogleButton(bootstrapData.googleClientId);else setStatus('Set GOOGLE_CLIENT_ID once in Apps Script properties to enable Gmail linking.',false)}catch(e){setStatus('Google connection setup unavailable: '+e.message,false)}}
  function renderGoogleButton(clientId){let tries=0;(function wait(){if(window.google&&google.accounts&&google.accounts.id){google.accounts.id.initialize({client_id:clientId,callback:handleGoogleCredential,auto_select:true,cancel_on_tap_outside:false});google.accounts.id.renderButton($('googleSignInButton'),{theme:'outline',size:'large',shape:'pill',text:'continue_with',width:280});if(!sessionValid(saved()))google.accounts.id.prompt();return}if(tries++<40)setTimeout(wait,250)})()}
  window.handleGoogleCredential=async function(response){const nonce=crypto.randomUUID();setStatus('Linking your Google account…',true);try{await post({action:'signin',credential:response.credential,nonce:nonce},true);let result=null;for(let i=0;i<12;i++){await new Promise(r=>setTimeout(r,500));const x=await jsonp('signinResult',{nonce:nonce},8000,true);if(x.status!=='PENDING'){result=x;break}}if(!result||!result.ok)throw Error(result&&result.error||'Account verification did not complete.');const c=saved();Object.assign(c,{sessionToken:result.sessionToken,sessionExpiry:Date.now()+Number(result.expiresIn||21600)*1000,email:result.email,url:endpoint()});store(c);fillForm();setStatus('Connected as '+result.email+'. Database and Drive will reconnect automatically.',true);await sync()}catch(e){setStatus('Google sign-in failed: '+e.message,false)}}
  function signOut(){const c=saved();delete c.sessionToken;delete c.sessionExpiry;delete c.email;store(c);if(window.google&&google.accounts)google.accounts.id.disableAutoSelect();fillForm();setStatus('Signed out. Local recording remains available.',false)}

  async function saveConfig(){const c=readForm();if(!c.url)return setStatus('Permanent backend endpoint is required once.',false);store(c);setStatus('Preferences saved.',true);if(!configured())return;try{await post({action:'config',retentionDays:c.retentionDays,model:c.model})}catch(e){setStatus('Saved locally; server update could not be confirmed.',false)}}
  async function test(){await saveConfig();if(!configured())return;setStatus('Testing Google backend…',true);try{const r=await jsonp('health');if(!r.ok)throw Error(r.error||'Connection failed');setStatus('Connected: database ✓ Drive ✓ Gemini '+(r.geminiConfigured?'✓':'key missing')+' • '+r.retentionDays+'-day audio retention • '+r.model,r.geminiConfigured)}catch(e){setStatus('Connection failed: '+e.message,false)}}
  async function sync(){if(!configured())return setStatus('Sign in with Google to synchronize history.',false);setStatus('Synchronizing local and Google history…',true);try{const r=await jsonp('list',{},45000);if(!r.ok)throw Error(r.error||'Sync failed');const local=await all(),byId=new Map(local.map(x=>[x.id,x])),remoteIds=new Set(r.sessions.map(x=>x.id));syncing=true;for(const remote of r.sessions){const prior=byId.get(remote.id);await oldPut(Object.assign({},prior||{},remote,{audio:prior&&prior.audio?prior.audio:null,cloudOnly:!prior}))}for(const row of local){if(!remoteIds.has(row.id))await cloudSave(row)}syncing=false;await render();updateFocus(r.sessions);setStatus((new Set(local.map(x=>x.id).concat(r.sessions.map(x=>x.id)))).size+' sessions synchronized.',true)}catch(e){syncing=false;setStatus('Sync failed: '+e.message,false)}}
  function updateFocus(rows){const latest=(rows||[]).filter(x=>x.aiReview&&x.aiStatus==='DONE').sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))[0];if(!latest)return;const r=latest.aiReview||{},leak=r.primaryLeak||r.primaryLever||'No major leak identified',drill=r.drill&&r.drill.instruction||r.assignedDrill||r.practiceChallenge||'Repeat the message once, more crisply.';$('latestLeak').textContent=leak;$('currentFocusTitle').textContent=String(r.drill&&r.drill.name||'NEXT COMMUNICATION LEVER').toUpperCase();$('currentFocusText').textContent=drill}

  function rubric(){const c=saved();return{model:c.model||'gemini-3.5-flash-lite',criteria:c.criteria||{},custom:c.custom||'',analysisVersion:'2.0',rubricVersion:'crisp-sharp-impactful-v1',mode:$('context').value}}
  async function analyzeWithAI(){if(!configured())return toast('Sign in with Google in Settings first.');const transcript=$('transcript').value.trim();if(!transcript)return toast('Record or enter a transcript first.');const jobId=crypto.randomUUID(),sessionId=$('sessionId').value||crypto.randomUUID(),m=analyze();$('sessionId').value=sessionId;$('aiReviewBtn').disabled=true;$('aiStatus').textContent='Saving session and starting communication review…';$('aiResult').hidden=true;try{await post({action:'save',session:{id:sessionId,createdAt:new Date().toISOString(),groupId:$('groupId').value,attempt:Number($('attemptNo').value)||1,title:$('title').value.trim()||'Untitled sample',context:$('context').value,audience:$('audience').value.trim(),duration:duration,transcript:transcript,timestampedTranscript:$('timestampedTranscript').value.trim(),reflection:$('reflection').value.trim(),tags:$('tags').value.trim(),metrics:m}});await post({action:'analyze',jobId:jobId,sessionId:sessionId,transcript:transcript,metrics:m,rubric:rubric()});const end=Date.now()+90000;let result;while(Date.now()<end){await new Promise(r=>setTimeout(r,2500));const j=await jsonp('job',{jobId:jobId});if(j.status==='DONE'){result=j.result;break}if(j.status==='ERROR')throw Error(j.error||'Gemini review failed')}if(!result)throw Error('Review is still processing. Try again shortly.');renderAI(result);updateFocus([{aiReview:result,aiStatus:'DONE',updatedAt:new Date().toISOString()}]);$('aiStatus').textContent='Communication review complete and linked to this session.'}catch(e){$('aiStatus').textContent='AI review unavailable: '+e.message}finally{$('aiReviewBtn').disabled=false}}
  function block(label,value,cls){return value?'<div class="coach '+(cls||'')+'"><b>'+esc(label)+'</b><span>'+esc(String(value))+'</span></div>':''}
  function renderAI(r){const scores=r.scores||{},scoreHtml=Object.entries(scores).filter(([,v])=>v!==null&&v!==undefined&&v!=='').map(([k,v])=>'<div><b>'+esc(String(v))+'</b><span>'+esc(k.replace(/([A-Z])/g,' $1'))+'</span></div>').join(''),worked=(r.whatWorked||r.strengths||[]).slice(0,2).join(' • '),drill=r.drill||{},compression=r.compression||{};$('aiResult').innerHTML='<h3>Crisp • Sharp • Impactful coaching</h3><p>'+esc(r.summary||'')+'</p><div class="review-grid">'+scoreHtml+'</div>'+block('What worked',worked,'strength')+block('Primary communication leak',r.primaryLeak||r.primaryLever,'focus')+block('Evidence',(r.evidence||[]).join(' • '),'')+block('Compression',compression.assessment||r.compressionAssessment,'')+(compression.rewrite?'<h4>Compressed version</h4><p class="detail-text">'+esc(compression.rewrite)+'</p>':'')+'<h4>Executive version</h4><p class="detail-text">'+esc(r.executiveVersion||r.tighterVersion||'')+'</p>'+(r.punchyVersion?'<h4>Punchy version</h4><p class="detail-text">'+esc(r.punchyVersion)+'</p>':'')+block('One drill',(drill.name?drill.name+': ':'')+(drill.instruction||r.assignedDrill||r.practiceChallenge||''),'challenge');$('aiResult').hidden=false}

  document.addEventListener('DOMContentLoaded',function(){fillForm();$('saveCloudBtn').onclick=saveConfig;$('testCloudBtn').onclick=test;$('syncCloudBtn').onclick=sync;$('aiReviewBtn').onclick=analyzeWithAI;$('signOutBtn').onclick=signOut;bootstrap();if(configured())setTimeout(sync,1200)});
})();
