/* Fluency OS V2.3 overlay for Csar090/fluent-me (current GitHub Pages structure). */
(function(){
  const STATE={activeTelegram:null,wordTimestamps:[]};window.FluencyV23=STATE;
  const endpoint=()=>String(window.FLUENCY_CONFIG?.backendUrl||'').trim().replace(/\/$/,'');
  const auth=()=>window.FluencyCloud.auth();
  function jsonp(action,params,timeout){return new Promise((resolve,reject)=>{const url=endpoint();if(!url)return reject(Error('Google backend is not configured.'));const name='fv23'+Date.now()+Math.random().toString(36).slice(2),s=document.createElement('script'),timer=setTimeout(()=>done(Error('Google backend timed out.')),timeout||30000);function done(err,data){clearTimeout(timer);delete window[name];s.remove();err?reject(err):resolve(data)}window[name]=d=>d&&d.ok===false?done(Error(d.error||'Google request failed')):done(null,d);s.onerror=()=>done(Error('Could not reach Google backend.'));s.referrerPolicy='no-referrer';s.src=url+'?'+new URLSearchParams(Object.assign({},params||{},auth(),{action,callback:name}));document.head.appendChild(s)})}
  async function post(payload){const url=endpoint();if(!url)throw Error('Google backend is not configured.');Object.assign(payload,auth());await fetch(url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)})}
  function fmt(s){s=Math.max(0,Math.round(Number(s)||0));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function timePrecise(v){v=Math.max(0,Number(v)||0);const m=Math.floor(v/60),s=v-m*60;return String(m).padStart(2,'0')+':'+s.toFixed(2).padStart(5,'0')}

  const previousTranscribe=window.transcribeRecordedAudio||transcribeRecordedAudio;
  window.transcribeRecordedAudio=transcribeRecordedAudio=async function(){
    const recordBtn=$('recordBtn'),saveBtn=$('saveBtn'),redoBtn=$('redoTranscriptBtn');recordBtn.disabled=true;saveBtn.disabled=true;if(redoBtn)redoBtn.disabled=true;
    $('status').textContent='Preparing complete local transcription';$('support').textContent='Processing this recording locally in your browser with word timestamps…';
    try{
      STATE.wordTimestamps=[];const model=await loadTranscriber();const prepared=await audioTo16k(blob);if(prepared.peak<0.0001)throw new Error('The recorded audio decoded as silence.');
      duration=Math.round(prepared.seconds);$('timer').textContent=fmt(duration);const output=await model(prepared.pcm,{return_timestamps:'word',chunk_length_s:25,stride_length_s:5});const result=Array.isArray(output)?output[0]:output,text=String(result?.text||'').trim();if(!text)throw new Error('The local speech model returned no words.');
      STATE.wordTimestamps=(result?.chunks||[]).map((c,i)=>{const t=Array.isArray(c.timestamp)?c.timestamp:[null,null];return{seq:i+1,word:String(c.text||'').trim(),startMs:Math.max(0,Math.round(Number(t[0]||0)*1000)),endMs:Math.max(0,Math.round(Number(t[1]??t[0]??0)*1000))}}).filter(x=>x.word);
      $('transcript').value=text;$('timestampedTranscript').value=STATE.wordTimestamps.map(w=>'['+timePrecise(w.startMs/1000)+'–'+timePrecise(w.endMs/1000)+'] '+w.word).join('\n');
      renderWordTimestampPanel();$('status').textContent='Complete local transcript ready';$('support').textContent='Local transcription, word timestamps and pause evidence are ready. Review, then save.';$('transcript').dispatchEvent(new Event('input',{bubbles:true}));metrics();
    }catch(e){$('status').textContent='Audio ready';$('support').textContent='On-device transcription could not finish: '+e.message+' Your recording is still available for playback.'}
    finally{recordBtn.disabled=false;saveBtn.disabled=false;if(redoBtn){redoBtn.disabled=false;redoBtn.hidden=!blob}}
  };

  function renderWordTimestampPanel(){const box=$('timestampSegments');if(!box)return;const words=STATE.wordTimestamps;box.classList.toggle('empty',!words.length);box.innerHTML=words.length?words.map(w=>'<button class="segment word-segment" data-start="'+(w.startMs/1000)+'"><b>'+timePrecise(w.startMs/1000)+'</b><span>'+esc(w.word)+'</span></button>').join(''):'Timestamped speech segments will appear here.';box.querySelectorAll('.segment').forEach(b=>b.onclick=()=>{$('playback').currentTime=Number(b.dataset.start);$('playback').play()});updateTimestampSummary()}
  function pauseMetrics(){const w=STATE.wordTimestamps,p=[];for(let i=1;i<w.length;i++)p.push(Math.max(0,w[i].startMs-w[i-1].endMs));const n=x=>p.filter(v=>v>=x).length;return{pauseCount:p.length,significantPauses:n(700),longPauses:n(1500),veryLongPauses:n(2500),maxPauseMs:p.length?Math.max(...p):0,avgPauseMs:p.length?Math.round(p.reduce((a,b)=>a+b,0)/p.length):0}}
  const baseAnalyze=analyze;analyze=function(){const m=baseAnalyze();const p=pauseMetrics();return Object.assign({},m,{fillerRate:m.rate,pauseMetrics:p,longPauses:p.longPauses,longestPause:p.maxPauseMs/1000,wordTimestampCount:STATE.wordTimestamps.length,timestampCoverageMs:STATE.wordTimestamps.length?STATE.wordTimestamps[STATE.wordTimestamps.length-1].endMs:0})};
  window.getFluencyExtendedMetrics=function(){return analyze()};
  window.getFluencyWordTimestamps=()=>STATE.wordTimestamps.slice();

  const baseReset=reset;reset=function(){STATE.activeTelegram=null;STATE.wordTimestamps=[];baseReset();$('aiResult').hidden=true;$('aiStatus').textContent=''};
  const oldPut=put;put=async function(row){if(row&&row.id===$('sessionId').value){row.wordTimestamps=STATE.wordTimestamps.slice();}if(STATE.activeTelegram&&row&&row.id===STATE.activeTelegram.id){row.source='TELEGRAM';row.sourceMessageId=STATE.activeTelegram.sourceMessageId||'';row.sourceFileUniqueId=STATE.activeTelegram.sourceFileUniqueId||'';row.sourceDurationMs=Number(STATE.activeTelegram.sourceDurationMs||row.duration*1000||0);row.transcriptionStatus=STATE.wordTimestamps.length?'COMPLETE':'READY_FOR_LOCAL_TRANSCRIPTION';row.wordTimestamps=STATE.wordTimestamps.slice();const cov=row.wordTimestamps.length?row.wordTimestamps[row.wordTimestamps.length-1].endMs:0;row.timestampCoverageMs=cov;row.timingVariancePct=row.sourceDurationMs?Math.round(((cov-row.sourceDurationMs)/row.sourceDurationMs)*1000)/10:0;row.integrityStatus=row.sourceDurationMs&&(cov>row.sourceDurationMs*1.10||cov<row.sourceDurationMs*.75)?'FAIL':'PASS';row.timestampSchemaVersion='WORD_V1';row.pauseMetricsJson=pauseMetrics()}return oldPut(row)};

  function updateTimestampSummary(){const el=$('timestampSummary');if(!el)return;const p=pauseMetrics();el.textContent=STATE.wordTimestamps.length?STATE.wordTimestamps.length+' words • '+p.significantPauses+' significant pauses':'Detailed evidence'}

  function mountTelegram(){if(document.getElementById('telegramInboxCard'))return;const hero=document.querySelector('#capture .hero'),card=document.createElement('article');card.id='telegramInboxCard';card.className='card telegram-card';card.innerHTML='<div class="telegram-head"><div><span class="eyebrow">MOBILE LONG-FORM INGESTION</span><h2>Telegram voice inbox</h2><p class="note">Telegram only brings the audio in. Transcription stays local in this browser.</p></div><div class="button-row"><button id="minimizeTelegramBtn" type="button">Minimize</button><button id="refreshTelegramBtn">Refresh</button></div></div><div id="telegramInboxBody"><p id="telegramConnection" class="note"></p><div id="telegramInboxList" class="telegram-list"><p class="note">Checking…</p></div></div>';hero.parentNode.insertBefore(card,hero);$('refreshTelegramBtn').onclick=refreshTelegram;window.FluencyWorkflow.collapse($('telegramInboxBody'),'Telegram voice inbox','telegram','minimizeTelegramBtn',$('minimizeTelegramBtn'));window.FluencyWorkflow.refreshShortcuts();const check=document.createElement('button');check.textContent='Check delivery';check.onclick=async()=>{check.disabled=true;try{const r=await jsonp('telegramStatus');$('telegramConnection').textContent=(r.deliveryMode==='POLLING'?'Delivery: automatic inbox check every minute • Last check: '+(r.lastCheckedAt||'pending'):'Pending deliveries: '+r.pendingUpdates)+' • Latest receipt: '+(r.lastReceivedAt||'none')+' • '+(r.lastError||'No delivery error reported.')+(r.webhookMatches?'':' • Delivery configuration needs attention.')}catch(e){$('telegramConnection').textContent='Delivery check failed: '+e.message+'. Update the backend if this action is unavailable.'}finally{check.disabled=false}};card.querySelector('.button-row').append(check);refreshTelegram()}
  let refreshing=false;
  async function refreshTelegram(){
    const list=$('telegramInboxList');if(!list||refreshing)return;
    const credentials=auth();if(!endpoint()||(!credentials.token&&!credentials.sessionToken)){list.innerHTML='<p class="note">Connect your Google account in Settings to load Telegram recordings.</p>';return}
    refreshing=true;$('refreshTelegramBtn').disabled=true;
    try{const r=await jsonp('list',{},45000);const rows=(r.sessions||[]).filter(x=>String(x.source).toUpperCase()==='TELEGRAM').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));
      const pending=rows.filter(x=>!String(x.transcript||'').trim()&&x.audioRetained&&x.transcriptionStatus!=='INGESTION_ERROR');
      const needsAttention=rows.filter(x=>!String(x.transcript||'').trim()&&(!x.audioRetained||x.transcriptionStatus==='INGESTION_ERROR'));
      $('telegramConnection').textContent='Inbox checked '+new Date().toLocaleTimeString()+'. '+pending.length+' awaiting transcription. Saved transcripts are in Library.';
      const item=(x,recover)=>'<div class="telegram-item"><div><b>'+esc(x.title||'Telegram recording')+'</b><small>'+esc(new Date(x.createdAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}))+' • '+fmt(x.duration)+' • '+esc(recover?(x.transcriptionStatus==='INGESTION_ERROR'?'Audio import failed':'Audio expired — resend to the bot'):(x.transcriptionStatus||'Ready for local transcription'))+'</small></div><button '+(recover?'data-restore-tg':'data-tg')+'="'+esc(x.id)+'">'+(recover?'Try restoring audio':'Open & transcribe locally')+'</button></div>';
      list.innerHTML=(pending.length?pending.map(x=>item(x,false)).join(''):'<p class="note">Inbox clear. Processed recordings are available in Library.</p>')+(needsAttention.length?'<details><summary>Needs attention ('+needsAttention.length+')</summary>'+needsAttention.map(x=>item(x,true)).join('')+'</details>':'');
      list.querySelectorAll('[data-tg]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await openTelegram(b.dataset.tg,rows.find(x=>x.id===b.dataset.tg))}finally{b.disabled=false}});
      list.querySelectorAll('[data-restore-tg]').forEach(b=>b.onclick=async()=>{b.disabled=true;b.textContent='Restoring…';try{const jobId=crypto.randomUUID();await post({action:'restoreTelegram',sessionId:b.dataset.restoreTg,jobId});let done=false;for(let i=0;i<12;i++){await new Promise(r=>setTimeout(r,2500));const job=await jsonp('job',{jobId});if(job.status==='ERROR')throw Error(job.error);if(job.status==='DONE'){done=true;break}}if(!done)throw Error('Restore not confirmed. The backend may need updating; resend the recording to the bot.');await refreshTelegram()}catch(e){b.textContent='Try restoring audio';b.disabled=false;toast(e.message)}});
    }catch(e){list.innerHTML='<p class="note cloud-warn">Telegram inbox unavailable: '+esc(e.message||e)+'. Check Settings → Test connection, then Refresh.</p>'}
    finally{refreshing=false;$('refreshTelegramBtn').disabled=false}
  }
  document.addEventListener('fluency-cloud-synced',refreshTelegram);
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshTelegram()});
  setInterval(()=>{if(!document.hidden)refreshTelegram()},60000);
  async function openTelegram(id,meta){if((blob||$('transcript').value.trim())&&$('sessionId').value!==id){if(!confirm('Save the current capture before opening Telegram audio?'))return;if(!await window.FluencyWorkflow.saveCapture())return;}try{$('status').textContent='Loading Telegram audio';const p=await jsonp('audio',{sessionId:id},60000);reset();STATE.wordTimestamps=[];const bin=atob(p.base64),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);blob=new Blob([a],{type:p.mimeType||'audio/ogg'});duration=Number(p.duration||meta?.duration||0);STATE.activeTelegram=Object.assign({},meta||{},{id:id,sourceDurationMs:Number(meta?.sourceDurationMs||duration*1000)});$('sessionId').value=id;$('groupId').value=meta?.groupId||id;$('attemptNo').value=meta?.attempt||1;$('attemptBadge').textContent='Attempt '+(meta?.attempt||1);$('title').value=meta?.title||'Telegram voice';$('context').value=meta?.context||'Conversation';$('timer').textContent=fmt(duration);$('playback').src=URL.createObjectURL(blob);$('playback').hidden=false;document.querySelector('button[data-tab="capture"]')?.click();document.querySelector('#capture .hero')?.scrollIntoView({behavior:'smooth',block:'start'});await transcribeRecordedAudio();}catch(e){toast('Telegram audio could not be opened: '+(e.message||e));$('status').textContent='Ready'}}

  document.addEventListener('DOMContentLoaded',mountTelegram);
})();
