/* Fluency OS V2.3 overlay for Csar090/fluent-me (current GitHub Pages structure). */
(function(){
  const STATE={activeTelegram:null,wordTimestamps:[]};window.FluencyV23=STATE;
  const KEY='fluency-cloud-v2',LEGACY_KEY='fluency-cloud-v1';
  const saved=()=>{try{return Object.assign({},JSON.parse(localStorage.getItem(LEGACY_KEY)||'{}'),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return{}}};
  const endpoint=()=>String((window.FLUENCY_CONFIG&&window.FLUENCY_CONFIG.backendUrl)||saved().url||'').trim().replace(/\/$/,'');
  const auth=()=>{const c=saved();return c.sessionToken&&Number(c.sessionExpiry||0)>Date.now()+30000?{sessionToken:c.sessionToken}:{token:c.token||''}};
  function jsonp(action,params,timeout){return new Promise((resolve,reject)=>{const url=endpoint();if(!url)return reject(Error('Google backend is not configured.'));const name='fv23'+Date.now()+Math.random().toString(36).slice(2),s=document.createElement('script'),timer=setTimeout(()=>done(Error('Google backend timed out.')),timeout||30000);function done(err,data){clearTimeout(timer);delete window[name];s.remove();err?reject(err):resolve(data)}window[name]=d=>done(null,d);s.onerror=()=>done(Error('Could not reach Google backend.'));s.src=url+'?'+new URLSearchParams(Object.assign({},params||{},auth(),{action,callback:name}));document.head.appendChild(s)})}
  async function post(payload){const url=endpoint();if(!url)throw Error('Google backend is not configured.');Object.assign(payload,auth());await fetch(url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)})}
  function fmt(s){s=Math.max(0,Math.round(Number(s)||0));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function timePrecise(v){v=Math.max(0,Number(v)||0);const m=Math.floor(v/60),s=v-m*60;return String(m).padStart(2,'0')+':'+s.toFixed(2).padStart(5,'0')}

  const previousTranscribe=window.transcribeRecordedAudio||transcribeRecordedAudio;
  window.transcribeRecordedAudio=transcribeRecordedAudio=async function(){
    const recordBtn=$('recordBtn'),saveBtn=$('saveBtn'),redoBtn=$('redoTranscriptBtn');recordBtn.disabled=true;saveBtn.disabled=true;if(redoBtn)redoBtn.disabled=true;
    $('status').textContent='Preparing complete local transcription';$('support').textContent='Processing this recording locally in your browser with word timestamps…';
    try{
      const model=await loadTranscriber();const prepared=await audioTo16k(blob);if(prepared.peak<0.0001)throw new Error('The recorded audio decoded as silence.');
      const output=await model(prepared.pcm,{return_timestamps:'word',chunk_length_s:25,stride_length_s:5});const result=Array.isArray(output)?output[0]:output,text=String(result?.text||'').trim();if(!text)throw new Error('The local speech model returned no words.');
      STATE.wordTimestamps=(result?.chunks||[]).map((c,i)=>{const t=Array.isArray(c.timestamp)?c.timestamp:[null,null];return{seq:i+1,word:String(c.text||'').trim(),startMs:Math.max(0,Math.round(Number(t[0]||0)*1000)),endMs:Math.max(0,Math.round(Number(t[1]??t[0]??0)*1000))}}).filter(x=>x.word);
      $('transcript').value=text;$('timestampedTranscript').value=STATE.wordTimestamps.map(w=>'['+timePrecise(w.startMs/1000)+'–'+timePrecise(w.endMs/1000)+'] '+w.word).join('\n');
      renderWordTimestampPanel();$('status').textContent='Complete local transcript ready';$('support').textContent='Local transcription, word timestamps and pause evidence are ready. Review, then save.';$('transcript').dispatchEvent(new Event('input',{bubbles:true}));metrics();
    }catch(e){$('status').textContent='Audio ready';$('support').textContent='On-device transcription could not finish: '+e.message+' Your recording is still available for playback.'}
    finally{recordBtn.disabled=false;saveBtn.disabled=false;if(redoBtn){redoBtn.disabled=false;redoBtn.hidden=!blob}}
  };

  function renderWordTimestampPanel(){const box=$('timestampSegments');if(!box)return;const words=STATE.wordTimestamps;box.classList.toggle('empty',!words.length);box.innerHTML=words.length?words.map(w=>'<button class="segment word-segment" data-start="'+(w.startMs/1000)+'"><b>'+timePrecise(w.startMs/1000)+'</b><span>'+esc(w.word)+'</span></button>').join(''):'Timestamped speech segments will appear here.';box.querySelectorAll('.segment').forEach(b=>b.onclick=()=>{$('playback').currentTime=Number(b.dataset.start);$('playback').play()});updateTimestampSummary()}
  function pauseMetrics(){const w=STATE.wordTimestamps,p=[];for(let i=1;i<w.length;i++)p.push(Math.max(0,w[i].startMs-w[i-1].endMs));const n=x=>p.filter(v=>v>=x).length;return{pauseCount:p.length,significantPauses:n(700),longPauses:n(1500),veryLongPauses:n(2500),maxPauseMs:p.length?Math.max(...p):0,avgPauseMs:p.length?Math.round(p.reduce((a,b)=>a+b,0)/p.length):0}}
  const baseAnalyze=analyze;analyze=function(){const m=baseAnalyze();const p=pauseMetrics();return Object.assign({},m,{fillerRate:m.rate,pauseMetrics:p,longPauses:p.longPauses,longestPause:p.maxPauseMs/1000,wordTimestampCount:STATE.wordTimestamps.length,timestampCoverageMs:STATE.wordTimestamps.length?STATE.wordTimestamps[STATE.wordTimestamps.length-1].endMs:0})};
  window.getFluencyExtendedMetrics=function(){return analyze()};
  window.getFluencyWordTimestamps=()=>STATE.wordTimestamps.slice();

  const oldPut=put;put=async function(row){if(STATE.activeTelegram&&row&&row.id===STATE.activeTelegram.id){row.source='TELEGRAM';row.sourceMessageId=STATE.activeTelegram.sourceMessageId||'';row.sourceFileUniqueId=STATE.activeTelegram.sourceFileUniqueId||'';row.sourceDurationMs=Number(STATE.activeTelegram.sourceDurationMs||row.duration*1000||0);row.transcriptionStatus='COMPLETE';row.wordTimestamps=STATE.wordTimestamps.slice();const cov=row.wordTimestamps.length?row.wordTimestamps[row.wordTimestamps.length-1].endMs:0;row.timestampCoverageMs=cov;row.timingVariancePct=row.sourceDurationMs?Math.round(((cov-row.sourceDurationMs)/row.sourceDurationMs)*1000)/10:0;row.integrityStatus=row.sourceDurationMs&&(cov>row.sourceDurationMs*1.10||cov<row.sourceDurationMs*.75)?'FAIL':'PASS';row.timestampSchemaVersion='WORD_V1';row.pauseMetricsJson=pauseMetrics()}return oldPut(row)};

  function mountCollapse(){const box=$('timestampSegments');if(!box||document.getElementById('timestampCollapseBtn'))return;const label=box.previousElementSibling,bar=document.createElement('div');bar.className='timestamp-toolbar';bar.innerHTML='<div><b>Word-timestamped transcription</b><span id="timestampSummary" class="note">Detailed evidence</span></div><button id="timestampCollapseBtn" type="button">Minimize</button>';if(label&&label.tagName==='LABEL')label.replaceWith(bar);else box.parentNode.insertBefore(bar,box);let collapsed=localStorage.getItem('fluency-ts-collapsed')==='1';const apply=()=>{box.hidden=collapsed;$('timestampCollapseBtn').textContent=collapsed?'Expand':'Minimize';localStorage.setItem('fluency-ts-collapsed',collapsed?'1':'0')};$('timestampCollapseBtn').onclick=()=>{collapsed=!collapsed;apply()};apply();updateTimestampSummary()}
  function updateTimestampSummary(){const el=$('timestampSummary');if(!el)return;const p=pauseMetrics();el.textContent=STATE.wordTimestamps.length?STATE.wordTimestamps.length+' words • '+p.significantPauses+' significant pauses':'Detailed evidence'}

  function mountTelegram(){if(document.getElementById('telegramInboxCard'))return;const hero=document.querySelector('#capture .hero'),card=document.createElement('article');card.id='telegramInboxCard';card.className='card telegram-card';card.innerHTML='<div class="telegram-head"><div><span class="eyebrow">MOBILE LONG-FORM INGESTION</span><h2>Telegram voice inbox</h2><p class="note">Telegram only brings the audio in. Transcription stays local in this browser.</p></div><button id="refreshTelegramBtn">Refresh</button></div><div id="telegramInboxList" class="telegram-list"><p class="note">Checking…</p></div>';hero.parentNode.insertBefore(card,hero);$('refreshTelegramBtn').onclick=refreshTelegram;refreshTelegram()}
  async function refreshTelegram(){const list=$('telegramInboxList');if(!endpoint()){list.innerHTML='<p class="note">Link the Google backend in Settings to use Telegram ingestion.</p>';return}try{const r=await jsonp('telegramPending',{},30000);const rows=r.sessions||[];list.innerHTML=rows.length?rows.map(x=>'<div class="telegram-item"><div><b>'+esc(x.title||'Telegram voice')+'</b><small>'+fmt(x.duration)+' • '+esc(x.transcriptionStatus||'READY')+'</small></div><button data-tg="'+esc(x.id)+'">Open & transcribe locally</button></div>').join(''):'<p class="note">No Telegram recordings waiting for transcription.</p>';list.querySelectorAll('[data-tg]').forEach(b=>b.onclick=()=>openTelegram(b.dataset.tg,rows.find(x=>x.id===b.dataset.tg)))}catch(e){list.innerHTML='<p class="note cloud-warn">Telegram inbox unavailable: '+esc(e.message||e)+'</p>'}}
  async function openTelegram(id,meta){try{$('status').textContent='Loading Telegram audio';const p=await jsonp('audio',{sessionId:id},60000);const bin=atob(p.base64),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);blob=new Blob([a],{type:p.mimeType||'audio/ogg'});duration=Number(p.duration||meta?.duration||0);STATE.activeTelegram=Object.assign({},meta||{},{id:id,sourceDurationMs:Number(meta?.sourceDurationMs||duration*1000)});$('sessionId').value=id;$('title').value=meta?.title||'Telegram voice';$('context').value=meta?.context||'Self-practice';$('timer').textContent=fmt(duration);$('playback').src=URL.createObjectURL(blob);$('playback').hidden=false;document.querySelector('button[data-tab="capture"]')?.click();document.querySelector('#capture .hero')?.scrollIntoView({behavior:'smooth',block:'start'});await transcribeRecordedAudio();if(STATE.wordTimestamps.length)await post({action:'saveWords',sessionId:id,words:STATE.wordTimestamps});}catch(e){toast('Telegram audio could not be opened: '+(e.message||e));$('status').textContent='Ready'}}

  function renderCoachV23(r){const target=$('aiResult');if(!target||!r)return;const s=r.scores||{},h=r.humor||{},needs=r.needsWork||[],next=r.nextPractice||[];const scoreKeys=[['North Star','northStar'],['Crispness','crispness'],['Structure','structure'],['Coherence','coherence'],['Clarity','clarity'],['Concision','concision'],['Impact','impact'],['Executive Presence','executivePresence'],['Delivery','delivery'],['Engagement','engagement'],['Humor / Wit','humorWit']];const scores=scoreKeys.filter(([,k])=>s[k]!=null).map(([n,k])=>'<div><b>'+Math.round(s[k])+'</b><span>'+esc(n)+'</span></div>').join('');const lenses=['North Star','Concise','Structured','Impactful','Executive','Conversational','Humor & Wit'];target.innerHTML='<h3>Communication Coach — Crisp • Sharp • Impactful</h3><p>'+esc(r.summary||'')+'</p><div class="coaching-lenses"><b>Coaching lenses</b><div>'+lenses.map(x=>'<button type="button" data-lens="'+esc(x)+'">'+esc(x)+'</button>').join('')+'</div><p id="lensInsight" class="note">One AI review; use these lenses to focus the same evidence without extra AI calls.</p></div><div class="review-grid">'+scores+'</div><div class="coach strength"><b>✓ What worked</b><span>'+esc((r.whatWorked||r.strengths||[]).join(' • ')||'—')+'</span></div><div class="coach focus"><b>△ What needs work</b><span>'+esc(needs.map(x=>(x.dimension?x.dimension+': ':'')+(x.issue||x.coach||'')).join(' • ')||r.primaryLeak||r.primaryLever||'—')+'</span></div><div class="coach challenge"><b>🎯 Next practice</b><span>'+esc(next.join(' • ')||r.drill?.instruction||r.practiceChallenge||'—')+'</span></div><div class="coach humor"><b>Humor & Wit</b><span>Applicability: '+esc(h.applicability||'N/A')+(h.opportunity?' • '+esc(h.opportunity):'')+(h.example?' • Example: '+esc(h.example):'')+'</span></div>'+(r.executiveVersion||r.tighterVersion?'<h4>Executive version</h4><p class="detail-text">'+esc(r.executiveVersion||r.tighterVersion)+'</p>':'')+(r.punchyVersion?'<h4>Punchier version</h4><p class="detail-text">'+esc(r.punchyVersion)+'</p>':'');target.querySelectorAll('[data-lens]').forEach(b=>b.onclick=()=>{const lens=b.dataset.lens,map={"North Star":'Overall: '+(s.northStar??'—')+'/100. Focus on whether the message is crisp, sharp and impactful as a whole.',"Concise":'Concision: '+(s.concision??'—')+'/100. '+(r.compression?.assessment||'Use fewer words without losing meaning.'),"Structured":'Structure: '+(s.structure??'—')+'/100; Coherence: '+(s.coherence??'—')+'/100. '+(r.architecture?.better||''),"Impactful":'Impact: '+(s.impact??'—')+'/100. '+(r.primaryLeak||''),"Executive":'Executive presence: '+(s.executivePresence??'—')+'/100. '+(r.executiveVersion||r.tighterVersion||''),"Conversational":'Engagement: '+(s.engagement??'—')+'/100. Keep natural delivery while preserving structure.',"Humor & Wit":'Applicability: '+(h.applicability||'N/A')+'. '+(h.opportunity||'No forced humor needed in this context.')};$('lensInsight').textContent=map[lens]||''});target.hidden=false}
  async function refreshLatestReview(){try{const sid=$('sessionId').value;if(!sid)return;const r=await jsonp('list',{},30000),row=(r.sessions||[]).find(x=>x.id===sid);if(row&&row.aiStatus==='DONE'&&row.aiReview)renderCoachV23(row.aiReview)}catch(e){}}
  document.addEventListener('click',e=>{if(e.target&&e.target.id==='aiReviewBtn')setTimeout(refreshLatestReview,5000)});

  document.addEventListener('DOMContentLoaded',()=>{mountCollapse();mountTelegram();const fs=document.querySelector('fieldset');if(fs&&!fs.querySelector('input[value="humorWit"]')){const l=document.createElement('label');l.className='check';l.innerHTML='<input class="criterion" type="checkbox" value="humorWit" checked> Humor & Wit (context-sensitive)';fs.appendChild(l)}const observer=new MutationObserver(()=>{const t=$('aiStatus');if(t&&/complete/i.test(t.textContent||''))refreshLatestReview()});if($('aiStatus'))observer.observe($('aiStatus'),{childList:true,subtree:true,characterData:true});});
})();
