const assert=require('node:assert/strict');
const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const {JSDOM}=require('jsdom');const {IDBFactory}=require('fake-indexeddb');
const root=path.join(__dirname,'..');const pause=()=>new Promise(r=>setTimeout(r,30));
async function app(remote=[],authorized=true){
 const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://example.test/',runScripts:'outside-only'});const w=dom.window;await pause();
 w.indexedDB=new IDBFactory();Object.defineProperty(w,'crypto',{value:require('node:crypto').webcrypto});w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({},{get:()=>()=>{}});w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};
 w.sessionStorage.setItem('fluency-auth-v2',JSON.stringify({sessionToken:'fixture-session',sessionExpiry:Date.now()+3600000,email:'fixture@gmail.com'}));w.localStorage.setItem('fluency-cloud-v2',JSON.stringify({model:'fixture-model',criteria:{structure:true,clarity:true}}));
 const jobs={},receipts={},requests=[];let failure=false;const realTimeout=w.setTimeout.bind(w);w.setTimeout=(fn,ms)=>realTimeout(fn,ms===2500||ms===1500?0:ms);w.setInterval=()=>0;
 w.fetch=async(url,opts)=>{const body=JSON.parse(opts.body);requests.push(body);if(body.action==='save'){const prior=remote.find(x=>x.id===body.session.id);if(prior)Object.assign(prior,body.session);else remote.push({...body.session});receipts[body.saveRequestId]={ok:true,status:'DONE',sessionId:body.session.id}}if(body.action==='analyze'){jobs[body.jobId]=failure?{ok:true,status:'ERROR',error:'Quota exhausted'}:{ok:true,status:'DONE',result:{summary:'Fixture review',scores:{structure:70},perspective:body.rubric.perspective,analyzedAt:new Date().toISOString()}}}return{}};
 const append=w.document.head.appendChild.bind(w.document.head);w.document.head.appendChild=el=>{if(el.tagName==='SCRIPT'&&el.src.includes('callback=')){const q=new URL(el.src).searchParams;queueMicrotask(()=>{const cb=w[q.get('callback')];if(!cb)return;const action=q.get('action');cb(action==='bootstrap'?{ok:true,authVersion:'google-v2',googleClientId:'fixture-client'}:!authorized?{ok:false,error:'UNAUTHORIZED'}:action==='session'?{ok:true,authVersion:'google-v2',email:'fixture@gmail.com',expiresAt:Date.now()+3600000,storageKey:Buffer.alloc(32,1).toString('base64')}:action==='list'?{ok:true,sessions:remote}:action==='job'?jobs[q.get('jobId')]||{ok:true,status:'PENDING'}:action==='saveResult'?receipts[q.get('saveRequestId')]||{ok:true,status:'PENDING'}:{ok:false,error:'Missing audio'})});return el}return append(el)};
 const ctx=dom.getInternalVMContext();for(const file of ['config.js','app.js','secure-storage.js','enhancements.js','cloud.js','fluency-v23.js','saved-reviews.js','progress.js','workflow.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});
 w.document.dispatchEvent(new w.Event('DOMContentLoaded'));await pause();await pause();
 return{w,ctx,remote,requests,fail:()=>failure=true,close:()=>w.close()};
}
(async()=>{
 const expired={id:'telegram-expired',createdAt:'2026-09-12T00:00:00Z',title:'Telegram voice',source:'TELEGRAM',transcript:'',metrics:{words:0,fillers:0,rate:0},audioRetained:false,transcriptionStatus:'READY_FOR_LOCAL_TRANSCRIPTION'};
 let a=await app([expired]);assert.match(a.w.document.getElementById('telegramInboxList').textContent,/Audio expired/);assert.match(a.w.document.getElementById('telegramInboxList').textContent,/Try restoring/);a.close();console.log('PASS: expired Telegram recordings remain visible');
 a=await app([],false);assert.equal(a.w.document.documentElement.classList.contains('auth-locked'),true);assert.match(a.w.document.getElementById('loginStatus').textContent,/UNAUTHORIZED/);assert.doesNotMatch(a.w.document.getElementById('telegramInboxList').textContent,/No Telegram recordings/);a.close();console.log('PASS: authorization errors are not empty inboxes');
 a=await app();let d=a.w.document;d.getElementById('title').value='Saved fixture';d.getElementById('transcript').value='The project is ready. Please approve the next step.';const id=d.getElementById('sessionId').value;await d.getElementById('saveBtn').onclick();await pause();let rows=await vm.runInContext('all()',a.ctx);assert.equal(rows.length,1);assert.equal(rows[0].id,id);assert.match(d.getElementById('samples').textContent,/AI review \/ perspectives/);await d.querySelector('[data-review]').onclick();assert.match(d.getElementById('sessionDetail').textContent,/Not yet reviewed/);assert.equal(d.querySelector('.saved-run').disabled,false);assert.equal(a.requests.filter(x=>x.action==='analyze').length,0);console.log('PASS: saving preserves identity and exposes review without auto-running Gemini');
 const savesBeforeReview=a.requests.filter(x=>x.action==='save').length;await a.w.FluencyReviews.run(rows[0],'structure','',()=>{});assert.equal(a.requests.filter(x=>x.action==='save').length,savesBeforeReview,'an already confirmed transcript must not be saved twice');const first=rows[0].aiReview;assert.equal(a.w.FluencyReviews.coverage(rows[0],'structure'),'Reviewed');assert.equal(a.w.FluencyReviews.coverage(rows[0],'humorWit'),'Not yet reviewed');await a.w.FluencyReviews.run(rows[0],'humorWit','Make it funny',()=>{});assert.equal(rows[0].aiReview.reviewHistory.length,1);assert.equal(rows[0].aiReview.reviewHistory[0].summary,first.summary);assert.equal(a.requests.filter(x=>x.action==='analyze')[1].rubric.perspective,'humorWit');console.log('PASS: confirmed transcripts start perspective reviews without redundant saves');
 a.fail();const prior=JSON.stringify(rows[0].aiReview);await assert.rejects(a.w.FluencyReviews.run(rows[0],'clarity','',()=>{}),/Quota/);assert.equal(JSON.stringify(rows[0].aiReview),prior);const encryptedRows=await new Promise(resolve=>{const request=a.w.indexedDB.open('fluency-os');request.onsuccess=()=>{const q=request.result.transaction('samples').objectStore('samples').getAll();q.onsuccess=()=>resolve(q.result)}});assert.equal(encryptedRows[0].sealed,1);assert.equal(encryptedRows[0].transcript,undefined);a.w.FluencyAccess.lock();assert.equal((await vm.runInContext('all()',a.ctx)).length,0);a.close();console.log('PASS: AI failure preserves review; stored transcripts are encrypted and inaccessible while locked');
 const backend=vm.createContext({console,LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})}});vm.runInContext(fs.readFileSync(path.join(root,'backend/Code.gs'),'utf8'),backend);
 assert.ok(backend.telegramMedia_({document:{file_name:'speech.mp3',mime_type:'application/octet-stream'}}));assert.equal(backend.telegramMedia_({document:{file_name:'notes.pdf',mime_type:'application/pdf'}}),null);assert.ok(backend.telegramMedia_({voice:{file_id:'voice'}}));console.log('PASS: Telegram voice, audio documents, and unsupported documents are classified correctly');
 let stored='{"summary":"Earlier review","scores":{"clarity":80}}';backend.sheet_=()=>({getRange:(row,col)=>({getValue:()=>stored,setValues:v=>{if(col===17)stored=v[0][1]}})});backend.findRow_=()=>2;backend.writeScoreHistory_=()=>{};backend.updateSessionStatus_('id','ERROR','Quota exhausted');assert.equal(JSON.parse(stored).summary,'Earlier review');backend.updateSessionReview_('id',{summary:'New review',scores:{impact:70}});assert.equal(JSON.parse(stored).reviewHistory[0].summary,'Earlier review');console.log('PASS: backend failure and new review preserve prior review evidence');
 a=await app();d=a.w.document;
 const style=d.createElement('style');style.textContent=fs.readFileSync(path.join(root,'styles.css'),'utf8')+fs.readFileSync(path.join(root,'fluency-v23.css'),'utf8');d.head.append(style);
 for(const id of ['telegramInboxBody','timestampSegments','transcriptBody']){const box=d.getElementById(id),button=d.getElementById(id==='telegramInboxBody'?'minimizeTelegramBtn':id+'Toggle');assert.ok(button,'the '+id+' minimize control must exist');assert.equal(button.getAttribute('aria-expanded'),'true');button.click();assert.equal(a.w.getComputedStyle(box).display,'none');assert.equal(button.textContent,'Expand');button.click();assert.notEqual(a.w.getComputedStyle(box).display,'none');}
 const transcriptButton=d.getElementById('transcriptBodyToggle');transcriptButton.click();a.w.HTMLElement.prototype.scrollIntoView=function(){this.dataset.scrolled='yes'};d.querySelector('[data-jump="transcriptBody"]').click();assert.equal(d.getElementById('transcriptBody').hidden,false);assert.equal(d.getElementById('transcriptBody').dataset.scrolled,'yes');
 d.querySelector('[data-tab="library"]').click();assert.equal(d.querySelector('[data-jump="librarySearchSection"]').hidden,false);assert.equal(d.querySelector('[data-jump="transcriptBody"]').hidden,true);d.querySelector('[data-tab="progress"]').click();assert.equal(d.querySelector('[data-jump="progressDimensionsSection"]').hidden,false);d.querySelector('[data-tab="settings"]').click();assert.equal(d.querySelector('[data-jump="settingsBackupSection"]').hidden,false);d.querySelector('[data-tab="capture"]').click();assert.equal(d.querySelector('[data-jump="telegramInboxBody"]').hidden,false);assert.equal(d.querySelector('[data-jump="reviewPanel"]').hidden,true);
 console.log('PASS: Telegram header and transcript minimize controls work; contextual shortcuts expand and navigate sections');
 const row={id:'practice',groupId:'practice',attempt:1,title:'Project decision',context:'Executive Briefing',audience:'Team',createdAt:new Date().toISOString(),transcript:'The project is ready to ship.',timestampedTranscript:'[00:00–00:02] The project',metrics:{words:6,fillers:0,transcriptRevision:1},aiStatus:'DONE',aiReview:{perspective:'all',transcriptRevision:1,scores:{structure:70,clarity:80,northStar:75},executiveVersion:'We are ready to ship.',punchyVersion:'Ready to ship.',humorousVersion:'The project is ready to leave the nest. I have packed its lunch.',drill:{instruction:'Lead with the decision.'}}};
 await a.w.FluencyCloud.saveLocal(row);a.w.FluencyReviews.open(row);assert.match(d.getElementById('sessionDetail').textContent,/packed its lunch/);assert.match(d.getElementById('sessionDetail').textContent,/Punchier version/);assert.doesNotMatch(d.getElementById('sessionDetail').textContent,/Executive take/);assert.equal(a.w.FluencyProgress.scores(row).clarity,80);
 const partial={...row,aiReview:{perspective:'humorWit',scores:{clarity:99},reviewHistory:[row.aiReview]}};assert.equal(a.w.FluencyProgress.scores(partial).clarity,80);assert.equal(a.w.FluencyProgress.scores({...row,metrics:{transcriptRevision:2}}).clarity,undefined);
 await a.w.FluencyWorkflow.edit(row);d.getElementById('transcript').value='The project will be ready tomorrow.';await a.w.FluencyWorkflow.saveCapture();rows=await vm.runInContext('all()',a.ctx);let corrected=rows.find(x=>x.id==='practice');assert.equal(corrected.metrics.transcriptRevision,2);assert.equal(corrected.metrics.timingTranscriptMatches,false);assert.equal(corrected.timestampedTranscript,row.timestampedTranscript);assert.equal(corrected.aiReview.executiveVersion,row.aiReview.executiveVersion);assert.equal(a.w.FluencyReviews.coverage(corrected,'clarity'),'Not yet reviewed');
 await a.w.FluencyWorkflow.nextAttempt(corrected);assert.equal(d.getElementById('attemptNo').value,'2');assert.equal(d.getElementById('groupId').value,'practice');assert.equal(d.getElementById('audience').value,'Team');assert.equal(d.getElementById('practiceFocus').textContent,'Lead with the decision.');assert.equal(d.getElementById('transcript').value,'');assert.notEqual(d.getElementById('sessionId').value,row.id);a.close();console.log('PASS: all three rewrites render, corrections retain history and timing, next attempt retains context and gets a new identity');
 const properties=new Map([['ALLOWED_EMAILS','fixture@gmail.com']]),cache=new Map();
 backend.PropertiesService={getScriptProperties:()=>({getProperty:k=>properties.get(k)||null,setProperty:(k,v)=>properties.set(k,v),deleteProperty:k=>properties.delete(k),getProperties:()=>Object.fromEntries(properties)})};backend.CacheService={getScriptCache:()=>({get:k=>cache.get(k)||null,put:(k,v)=>cache.set(k,v),remove:k=>cache.delete(k)})};backend.Utilities={getUuid:()=>require('node:crypto').randomUUID(),DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(a,s)=>require('node:crypto').createHash(a).update(s).digest(),base64EncodeWebSafe:b=>Buffer.from(b).toString('base64url')};backend.verifyGoogleCredential_=()=>({email:'fixture@gmail.com',sub:'fixture',expiresAt:Date.now()+60000});backend.recordUser_=()=>{};
 backend.signin_({nonce:'test-session-nonce-1234',credential:'fixture'});const signed=backend.signinResult_('test-session-nonce-1234');assert.equal(signed.expiresIn,28800);cache.clear();assert.equal(backend.authenticatedUser_({sessionToken:signed.sessionToken}).email,'fixture@gmail.com');properties.set('ALLOWED_EMAILS','');assert.equal(backend.authenticatedUser_({sessionToken:signed.sessionToken}),null);properties.set('ALLOWED_EMAILS','fixture@gmail.com');assert.equal(backend.authenticatedUser_({sessionToken:signed.sessionToken}),null);
 console.log('PASS: eight-hour sessions survive cache eviction; removed access revokes the durable session');
 backend.saveSession_=()=>{throw Error('Transcript revision conflict')};assert.throws(()=>backend.saveWithReceipt_({saveRequestId:'fixture-save-request-1234',session:{id:'fixture'}}),/Transcript revision conflict/);assert.match(backend.saveResult_('fixture-save-request-1234').error,/Transcript revision conflict/);backend.saveSession_=s=>({ok:true,id:s.id});backend.saveWithReceipt_({saveRequestId:'fixture-success-request-1234',session:{id:'fixture'}});assert.equal(backend.saveResult_('fixture-success-request-1234').status,'DONE');console.log('PASS: backend save receipts expose success and exact save errors');
 properties.set('TELEGRAM_DELIVERY_MODE','POLLING');backend.LockService.getUserLock=()=>({tryLock:()=>true,releaseLock(){}});backend.PropertiesService.getScriptProperties=()=>({getProperty:k=>properties.get(k)||null,setProperty:(k,v)=>properties.set(k,v),setProperties:o=>Object.entries(o).forEach(([k,v])=>properties.set(k,v)),deleteProperty:k=>properties.delete(k),getProperties:()=>Object.fromEntries(properties)});
 backend.telegramApi_=()=>({ok:true,result:[{update_id:42},{update_id:43}]});const imported=[];backend.handleTelegramUpdate_=u=>{if(u.update_id===43)throw Error('Temporary download error');imported.push(u.update_id);return{ok:true,sessionId:'test'}};assert.throws(()=>backend.Telegram_poll(),/Temporary/);assert.equal(properties.get('TELEGRAM_UPDATE_OFFSET'),'43');assert.deepEqual(imported,[42]);assert.match(properties.get('TELEGRAM_POLL_ERROR'),/Temporary/);backend.telegramApi_=()=>({ok:true,result:[{update_id:43}]});backend.handleTelegramUpdate_=()=>({ok:true,sessionId:'retry'});backend.Telegram_poll();assert.equal(properties.get('TELEGRAM_UPDATE_OFFSET'),'44');assert.equal(properties.get('TELEGRAM_POLL_ERROR'),'');console.log('PASS: Telegram polling advances only after successful ingestion and retries failed updates');
 console.log('All regression scenarios passed. No live Gemini calls or production writes.');
})().catch(e=>{console.error(e);process.exitCode=1});
