const assert=require('node:assert/strict');
const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const {JSDOM}=require('jsdom');const {IDBFactory}=require('fake-indexeddb');
const root=path.join(__dirname,'..');const pause=()=>new Promise(r=>setTimeout(r,30));
async function app(remote=[],authorized=true){
 const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://example.test/',runScripts:'outside-only'});const w=dom.window;await pause();
 w.indexedDB=new IDBFactory();Object.defineProperty(w,'crypto',{value:require('node:crypto').webcrypto});w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({},{get:()=>()=>{}});w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};
 w.sessionStorage.setItem('fluency-auth-v2',JSON.stringify({sessionToken:'fixture-session',sessionExpiry:Date.now()+3600000,email:'fixture@gmail.com'}));w.localStorage.setItem('fluency-cloud-v2',JSON.stringify({model:'fixture-model',criteria:{structure:true,clarity:true}}));
 const jobs={},requests=[];let failure=false;const realTimeout=w.setTimeout.bind(w);w.setTimeout=(fn,ms)=>realTimeout(fn,ms===2500?0:ms);w.setInterval=()=>0;
 w.fetch=async(url,opts)=>{const body=JSON.parse(opts.body);requests.push(body);if(body.action==='save'){const prior=remote.find(x=>x.id===body.session.id);if(prior)Object.assign(prior,body.session);else remote.push({...body.session})}if(body.action==='analyze'){jobs[body.jobId]=failure?{ok:true,status:'ERROR',error:'Quota exhausted'}:{ok:true,status:'DONE',result:{summary:'Fixture review',scores:{structure:70},perspective:body.rubric.perspective,analyzedAt:new Date().toISOString()}}}return{}};
 const append=w.document.head.appendChild.bind(w.document.head);w.document.head.appendChild=el=>{if(el.tagName==='SCRIPT'&&el.src.includes('callback=')){const q=new URL(el.src).searchParams;queueMicrotask(()=>{const cb=w[q.get('callback')];if(!cb)return;const action=q.get('action');cb(action==='bootstrap'?{ok:true,authVersion:'google-v2',googleClientId:'fixture-client'}:!authorized?{ok:false,error:'UNAUTHORIZED'}:action==='session'?{ok:true,authVersion:'google-v2',email:'fixture@gmail.com',expiresAt:Date.now()+3600000,storageKey:Buffer.alloc(32,1).toString('base64')}:action==='list'?{ok:true,sessions:remote}:action==='job'?jobs[q.get('jobId')]||{ok:true,status:'PENDING'}:{ok:false,error:'Missing audio'})});return el}return append(el)};
 const ctx=dom.getInternalVMContext();for(const file of ['config.js','app.js','secure-storage.js','enhancements.js','cloud.js','fluency-v23.js','saved-reviews.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});
 w.document.dispatchEvent(new w.Event('DOMContentLoaded'));await pause();await pause();
 return{w,ctx,remote,requests,fail:()=>failure=true,close:()=>w.close()};
}
(async()=>{
 const expired={id:'telegram-expired',createdAt:'2026-09-12T00:00:00Z',title:'Telegram voice',source:'TELEGRAM',transcript:'',metrics:{words:0,fillers:0,rate:0},audioRetained:false,transcriptionStatus:'READY_FOR_LOCAL_TRANSCRIPTION'};
 let a=await app([expired]);assert.match(a.w.document.getElementById('telegramInboxList').textContent,/Audio expired/);assert.match(a.w.document.getElementById('telegramInboxList').textContent,/Try restoring/);a.close();console.log('PASS: expired Telegram recordings remain visible');
 a=await app([],false);assert.equal(a.w.document.documentElement.classList.contains('auth-locked'),true);assert.match(a.w.document.getElementById('loginStatus').textContent,/UNAUTHORIZED/);assert.doesNotMatch(a.w.document.getElementById('telegramInboxList').textContent,/No Telegram recordings/);a.close();console.log('PASS: authorization errors are not empty inboxes');
 a=await app();let d=a.w.document;d.getElementById('title').value='Saved fixture';d.getElementById('transcript').value='The project is ready. Please approve the next step.';const id=d.getElementById('sessionId').value;await d.getElementById('saveBtn').onclick();await pause();let rows=await vm.runInContext('all()',a.ctx);assert.equal(rows.length,1);assert.equal(rows[0].id,id);assert.match(d.getElementById('samples').textContent,/AI review \/ perspectives/);await d.querySelector('[data-review]').onclick();assert.match(d.getElementById('sessionDetail').textContent,/Not yet reviewed/);assert.equal(d.querySelector('.saved-run').disabled,false);assert.equal(a.requests.filter(x=>x.action==='analyze').length,0);console.log('PASS: saving preserves identity and exposes review without auto-running Gemini');
 await a.w.FluencyReviews.run(rows[0],'structure','',()=>{});const first=rows[0].aiReview;assert.equal(a.w.FluencyReviews.coverage(rows[0],'structure'),'Reviewed');assert.equal(a.w.FluencyReviews.coverage(rows[0],'humorWit'),'Not yet reviewed');await a.w.FluencyReviews.run(rows[0],'humorWit','Make it funny',()=>{});assert.equal(rows[0].aiReview.reviewHistory.length,1);assert.equal(rows[0].aiReview.reviewHistory[0].summary,first.summary);assert.equal(a.requests.filter(x=>x.action==='analyze')[1].rubric.perspective,'humorWit');console.log('PASS: subsequent perspective reviews preserve earlier reviews');
 a.fail();const prior=JSON.stringify(rows[0].aiReview);await assert.rejects(a.w.FluencyReviews.run(rows[0],'clarity','',()=>{}),/Quota/);assert.equal(JSON.stringify(rows[0].aiReview),prior);const encryptedRows=await new Promise(resolve=>{const request=a.w.indexedDB.open('fluency-os');request.onsuccess=()=>{const q=request.result.transaction('samples').objectStore('samples').getAll();q.onsuccess=()=>resolve(q.result)}});assert.equal(encryptedRows[0].sealed,1);assert.equal(encryptedRows[0].transcript,undefined);a.w.FluencyAccess.lock();assert.equal((await vm.runInContext('all()',a.ctx)).length,0);a.close();console.log('PASS: AI failure preserves review; stored transcripts are encrypted and inaccessible while locked');
 const backend=vm.createContext({console});vm.runInContext(fs.readFileSync(path.join(root,'backend/Code.gs'),'utf8'),backend);
 assert.ok(backend.telegramMedia_({document:{file_name:'speech.mp3',mime_type:'application/octet-stream'}}));assert.equal(backend.telegramMedia_({document:{file_name:'notes.pdf',mime_type:'application/pdf'}}),null);assert.ok(backend.telegramMedia_({voice:{file_id:'voice'}}));console.log('PASS: Telegram voice, audio documents, and unsupported documents are classified correctly');
 let stored='{"summary":"Earlier review","scores":{"clarity":80}}';backend.sheet_=()=>({getRange:(row,col)=>({getValue:()=>stored,setValues:v=>{if(col===17)stored=v[0][1]}})});backend.findRow_=()=>2;backend.writeScoreHistory_=()=>{};backend.updateSessionStatus_('id','ERROR','Quota exhausted');assert.equal(JSON.parse(stored).summary,'Earlier review');backend.updateSessionReview_('id',{summary:'New review',scores:{impact:70}});assert.equal(JSON.parse(stored).reviewHistory[0].summary,'Earlier review');console.log('PASS: backend failure and new review preserve prior review evidence');
 console.log('All 7 regression scenarios passed. No live Gemini calls or production writes.');
})().catch(e=>{console.error(e);process.exitCode=1});
