(function(){
  const $=id=>document.getElementById(id);
  const state={draft:null,answers:{},ignored:[],recorder:null,stream:null,chunks:[]};
  const endpoint=()=>String((window.REL_CONFIG&&REL_CONFIG.backendUrl)||localStorage.getItem('rel-backend-url')||'').trim().replace(/\/$/,'');
  const status=t=>$('status').textContent=t;
  function jsonp(action,params={},timeout=30000){return new Promise((resolve,reject)=>{const url=endpoint();if(!url)return reject(Error('Backend URL is not configured.'));const cb='relCb'+Date.now()+Math.random().toString(36).slice(2),s=document.createElement('script');const timer=setTimeout(()=>done(Error('Backend timed out.')),timeout);function done(e,d){clearTimeout(timer);delete window[cb];s.remove();e?reject(e):resolve(d)}window[cb]=d=>done(null,d);s.onerror=()=>done(Error('Could not reach Google backend.'));s.src=url+'?'+new URLSearchParams({...params,action,callback:cb});document.head.appendChild(s)})}
  async function post(payload){const url=endpoint();if(!url)throw Error('Backend URL is not configured.');const nonce=crypto.randomUUID();payload.nonce=nonce;await fetch(url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,500));const x=await jsonp('rpcResult',{nonce},8000);if(x&&x.status!=='PENDING'){if(!x.ok)throw Error(x.error||'Backend error');return x.result}}throw Error('Backend did not return a result.')}
  async function rpc(fn,...args){return post({action:'rpc',fn,args})}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function blob64(b){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(b)})}
  async function speak(){if(state.recorder&&state.recorder.state==='recording'){state.recorder.stop();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){status('Microphone recording is unavailable in this browser. Use Write.');return}try{status('Requesting microphone access…');state.stream=await navigator.mediaDevices.getUserMedia({audio:true});state.chunks=[];state.recorder=new MediaRecorder(state.stream);state.recorder.ondataavailable=e=>{if(e.data.size)state.chunks.push(e.data)};state.recorder.onstart=()=>{$('speak').textContent='■ Stop recording';status('Recording…')};state.recorder.onstop=async()=>{try{$('speak').textContent='🎙 Speak';const blob=new Blob(state.chunks,{type:state.recorder.mimeType||'audio/webm'});state.stream.getTracks().forEach(t=>t.stop());status('Transcribing…');const result=await rpc('transcribeCaptureAudio',await blob64(blob),blob.type);$('capture').value=[$('capture').value.trim(),result.transcript].filter(Boolean).join('\n');status('Transcript ready. Edit if needed, then Structure capture.')}catch(e){status(e.message)}};state.recorder.start()}catch(e){status(e.name==='NotAllowedError'?'Microphone permission was blocked. Allow it for this GitHub Pages site and retry.':e.message)}}
  async function structure(){const text=$('capture').value.trim();if(!text)return status('Write or record something first.');try{status('Structuring and checking completeness…');state.answers={};state.ignored=[];render(await rpc('analyzeCapture',text))}catch(e){status(e.message)}}
  function render(d){state.draft=d;const a=d.fieldAssessment||[],counts={captured:0,needs_clarification:0,not_applicable:0,ignored_intentionally:0};a.forEach(x=>counts[x.state]=(counts[x.state]||0)+1);$('draft').innerHTML='<h3>'+esc(d.recordType)+'</h3><p><b>Completeness:</b> Captured '+counts.captured+' · Clarify '+counts.needs_clarification+' · N/A '+counts.not_applicable+' · Ignored '+counts.ignored_intentionally+'</p><details><summary>Field-by-field</summary>'+a.map(x=>'<p><b>'+esc(x.label||x.field)+'</b> — '+esc(x.state.replaceAll('_',' '))+(x.reason?' · '+esc(x.reason):'')+'</p>').join('')+'</details>'+(d.readyToSave?'<button id="saveDraft">Save to Needs Your Review</button>':'');if(d.readyToSave)$('saveDraft').onclick=save;renderQuestions(d.followUpQuestions||[]);status(d.readyToSave?'Completeness check passed.':'Answer or intentionally ignore the questions below.')}
  function renderQuestions(qs){$('questions').innerHTML=qs.length?'<section class="card"><h3>Clarifications</h3>'+qs.map((q,i)=>'<div class="q" data-id="'+esc(q.id)+'"><b>'+(i+1)+'. '+esc(q.question)+'</b><small>'+esc(q.whyNeeded||'')+'</small><textarea id="a_'+esc(q.id)+'" placeholder="Answer naturally…"></textarea><button class="ignore" data-id="'+esc(q.id)+'">Ignore for this record</button></div>').join('')+'<button id="updateDraft">Update capture</button><button id="ignoreAll">Ignore remaining & save</button></section>':'';document.querySelectorAll('.ignore').forEach(b=>b.onclick=()=>{if(!state.ignored.includes(b.dataset.id))state.ignored.push(b.dataset.id);b.closest('.q').classList.add('ignored')});if($('updateDraft'))$('updateDraft').onclick=()=>refine(false);if($('ignoreAll'))$('ignoreAll').onclick=()=>refine(true)}
  async function refine(all){const qs=state.draft.followUpQuestions||[];qs.forEach(q=>{const v=$('a_'+q.id)?.value.trim();if(v)state.answers[q.id]=v;if(all&&!state.ignored.includes(q.id))state.ignored.push(q.id)});try{status('Re-evaluating complete capture…');const d=await rpc('refineCapture',$('capture').value.trim(),state.draft,state.answers,state.ignored);render(d);if(all&&d.readyToSave)await save()}catch(e){status(e.message)}}
  async function save(){try{status('Saving to Needs Your Review…');await rpc('saveCaptureDraft',state.draft);status('Saved.');$('capture').value='';$('draft').innerHTML='';$('questions').innerHTML='';await load()}catch(e){status(e.message)}}
  async function load(){if(!endpoint())return;try{const d=await rpc('getDashboardData');$('activity').textContent=JSON.stringify(d,null,2);const q=await rpc('getReviewQueue');$('review').textContent=JSON.stringify(q,null,2);const i=await rpc('getInsightsData');$('insights').textContent=JSON.stringify(i,null,2)}catch(e){status(e.message)}}
  $('speak').onclick=speak;$('write').onclick=()=>$('capture').focus();$('structure').onclick=structure;$('saveBackend').onclick=()=>{localStorage.setItem('rel-backend-url',$('backend').value.trim());status('Backend URL saved on this device.');load()};$('backend').value=endpoint();if(location.protocol==='https:'&&navigator.mediaDevices?.getUserMedia)status('Microphone API available on this HTTPS page.');else status('Microphone API unavailable.');load();
})();